# Generated by Django 4.1.5 on 2023-03-11 13:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False, unique=True)),
                ('department', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='subteam', to='timelog.department')),
            ],
        ),
        migrations.CreateModel(
            name='TimeLogEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log_year', models.IntegerField()),
                ('log_month', models.IntegerField()),
                ('log_day', models.IntegerField()),
                ('log_date', models.DateField()),
                ('log_in_time', models.TimeField()),
                ('log_out_time', models.TimeField(null=True)),
                ('log_state', models.IntegerField(choices=[(0, 'unsettled'), (1, 'settled'), (2, 'approval pending')])),
                ('interval_time', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('login_name', models.CharField(max_length=100, primary_key=True, serialize=False, unique=True)),
                ('sap_id', models.CharField(max_length=10, unique=True)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email_id', models.EmailField(max_length=100)),
                ('status', models.IntegerField(choices=[(0, 'inactive'), (1, 'active')], default=1)),
                ('department', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='timelog.department')),
                ('team', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='timelog.team')),
            ],
        ),
        migrations.CreateModel(
            name='UserTimeSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('net_working_time', models.IntegerField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='timelog.user')),
            ],
        ),
        migrations.CreateModel(
            name='UserTimeRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('month', models.IntegerField()),
                ('day', models.IntegerField()),
                ('date', models.DateField()),
                ('week_day', models.CharField(max_length=15)),
                ('mandatory_work_time', models.IntegerField()),
                ('mandatory_break_time', models.IntegerField()),
                ('total_work_time_for_day', models.IntegerField()),
                ('log_entries', models.ManyToManyField(default=[], to='timelog.timelogentry')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timelog.user')),
            ],
        ),
        migrations.CreateModel(
            name='UserLiveStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_update', models.DateTimeField()),
                ('live_state', models.IntegerField(choices=[(0, 'out'), (1, 'in')])),
                ('active_log', models.IntegerField(default=-1)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='timelog.user')),
            ],
        ),
        migrations.CreateModel(
            name='UserDefault',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mandatory_break_time', models.IntegerField()),
                ('mandatory_working_time_per_day', models.IntegerField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='timelog.user')),
            ],
        ),
        migrations.AddField(
            model_name='timelogentry',
            name='log_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timelog.user'),
        ),
        migrations.CreateModel(
            name='TimeLogCorrectionRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_id', models.IntegerField()),
                ('entry_date', models.DateField()),
                ('entry_in_time', models.TimeField()),
                ('entry_out_time', models.TimeField()),
                ('approver_decision', models.IntegerField(choices=[(-1, 'decision pending'), (0, 'rejected'), (1, 'approved')])),
                ('request_date', models.DateField()),
                ('request_year', models.IntegerField()),
                ('request_month', models.IntegerField()),
                ('decision_date', models.DateField(null=True)),
                ('approver', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tba_by', to='timelog.user')),
                ('requester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requested_by', to='timelog.user')),
            ],
        ),
        migrations.AddField(
            model_name='team',
            name='manager',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='incharge', to='timelog.user'),
        ),
        migrations.AddField(
            model_name='team',
            name='time_log_correction_approver',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='time_log_approver', to='timelog.user'),
        ),
        migrations.AddField(
            model_name='department',
            name='incharge',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='hod', to='timelog.user'),
        ),
    ]
