# Generated by Django 4.1.5 on 2023-01-09 11:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('timelog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='manager',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='incharge', to='timelog.user'),
        ),
        migrations.AlterField(
            model_name='team',
            name='time_log_correction_approver',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='time_log_approver', to='timelog.user'),
        ),
    ]
