# Generated by Django 4.1.5 on 2023-01-03 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timelog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email_id',
            field=models.EmailField(max_length=100),
        ),
        migrations.CreateModel(
            name='TimeLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.TimeField()),
                ('type', models.IntegerField(choices=[(0, 'punch_in'), (1, 'punch_out')])),
                ('user', models.ManyToManyField(to='timelog.user')),
            ],
        ),
    ]
