# Generated by Django 4.1.5 on 2023-03-19 18:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('timelog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConflictGroup',
            fields=[
                ('id', models.CharField(max_length=30, primary_key=True, serialize=False, unique=True)),
                ('status', models.IntegerField(choices=[(0, 'active'), (1, 'disabled')])),
                ('members', models.ManyToManyField(default=[], to='timelog.user')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timelog.team')),
            ],
        ),
    ]
