# Generated by Django 4.1.5 on 2023-03-11 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timelog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='timelogcorrectionrequest',
            name='remark',
            field=models.CharField(default='', max_length=200),
        ),
    ]
