# Generated by Django 4.1.5 on 2023-01-03 21:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('timelog', '0002_alter_user_email_id_timelog'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timelog',
            name='user',
        ),
        migrations.AddField(
            model_name='timelog',
            name='user',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to='timelog.user'),
            preserve_default=False,
        ),
    ]
