# Generated by Django 4.1.4 on 2022-12-29 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timelog', '0002_userdefaults'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='login_name',
            field=models.CharField(default='rvoduru', max_length=100),
            preserve_default=False,
        ),
    ]
