# Generated by Django 4.1.5 on 2023-01-03 22:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timelog', '0003_remove_timelog_user_timelog_user'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TimeLog',
            new_name='TimeLogEntry',
        ),
    ]
