# Generated by Django 4.1.5 on 2023-01-09 22:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('timelog', '0003_alter_user_department_alter_user_team'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimeLogCorrectionRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_id', models.IntegerField()),
                ('entry_date', models.DateField()),
                ('entry_in_time', models.TimeField()),
                ('entry_out_time', models.TimeField()),
                ('approver_decision', models.IntegerField(choices=[(-1, 'decision pending'), (0, 'rejected'), (1, 'approved')])),
                ('request_date', models.DateField()),
                ('decision_date', models.DateField(null=True)),
                ('approver', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tba_by', to='timelog.user')),
                ('requester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requested_by', to='timelog.user')),
            ],
        ),
    ]
