# Generated by Django 4.1.5 on 2023-01-03 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timelog', '0004_rename_timelog_timelogentry'),
    ]

    operations = [
        migrations.AddField(
            model_name='timelogentry',
            name='date',
            field=models.DateField(),
            preserve_default=False,
        ),
    ]
