# Generated by Django 4.1.5 on 2023-01-10 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timelog', '0004_timelogcorrectionrequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timelogentry',
            name='log_state',
            field=models.IntegerField(choices=[(0, 'unsettled'), (1, 'settled'), (2, 'approval pending')]),
        ),
    ]
