# Generated by Django 4.1.5 on 2023-01-03 22:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('timelog', '0005_timelogentry_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='timelogentry',
            old_name='date',
            new_name='log_date',
        ),
        migrations.RenameField(
            model_name='timelogentry',
            old_name='timestamp',
            new_name='log_time',
        ),
        migrations.RenameField(
            model_name='timelogentry',
            old_name='type',
            new_name='log_type',
        ),
        migrations.RenameField(
            model_name='timelogentry',
            old_name='user',
            new_name='log_user',
        ),
        migrations.CreateModel(
            name='UserLiveStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.IntegerField(choices=[(0, 'out'), (1, 'in')])),
                ('total_work_time', models.IntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timelog.user')),
            ],
        ),
    ]
