# Generated by Django 4.1.5 on 2023-01-12 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timelog', '0005_alter_timelogentry_log_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='timelogentry',
            name='interval_time',
            field=models.IntegerField(default=0),
        ),
    ]
