# Generated by Django 4.1.5 on 2023-01-03 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timelog', '0006_rename_date_timelogentry_log_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timelogentry',
            name='log_type',
            field=models.IntegerField(choices=[(0, 'punch_out'), (1, 'punch_in')]),
        ),
    ]
